[colors]
background = "#0d1117"
foreground = "#e6edf3"
selection-background = "#2f81f7"
selection-foreground = "#ffffff"
tabs-active = "#e6edf3"
tabs-foreground = "#848d97"
tabs-active-highlight = "#f78166"
bar = "#0d1117"
cursor = "#2f81f7"
vi-cursor = "#2f81f7"
search-match-background = "#f2cc60"
search-match-foreground = "#e6edf3"
search-focused-match-background = "#9e6a03"
search-focused-match-foreground = "#e6edf3"
black = "#484f58"
blue = "#58a6ff"
cyan = "#39c5cf"
green = "#3fb950"
magenta = "#bc8cff"
red = "#ff7b72"
white = "#b1bac4"
yellow = "#d29922"
light-black = "#6e7681"
light-blue = "#79c0ff"
light-cyan = "#56d4dd"
light-green = "#56d364"
light-magenta = "#d2a8ff"
light-red = "#ffa198"
light-white = "#ffffff"
light-yellow = "#e3b341"
light-foreground = "#848d97"