[colors]
background = "#ffffff"
foreground = "#1f2328"
selection-background = "#0969da"
selection-foreground = "#ffffff"
tabs-active = "#1f2328"
tabs-foreground = "#656d76"
tabs-active-highlight = "#fd8c73"
bar = "#ffffff"
cursor = "#0969da"
vi-cursor = "#0969da"
search-match-background = "#fae17d"
search-match-foreground = "#1f2328"
search-focused-match-background = "#9a6700"
search-focused-match-foreground = "#1f2328"
black = "#24292f"
blue = "#0969da"
cyan = "#1b7c83"
green = "#116329"
magenta = "#8250df"
red = "#cf222e"
white = "#6e7781"
yellow = "#4d2d00"
light-black = "#57606a"
light-blue = "#218bff"
light-cyan = "#3192aa"
light-green = "#1a7f37"
light-magenta = "#a475f9"
light-red = "#a40e26"
light-white = "#8c959f"
light-yellow = "#633c01"
light-foreground = "#656d76"